kind: pipeline
name: default

steps:
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  environment:
    DRONE_REPO: simcu_wechat-gateway
  settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token